---
- name: Set up local sysadmin tooling.
  hosts: local
  roles:
    - {role: git, tags: ['git']}
    - {role: vim, tags: ['vim, bootstrap']}
    - {role: rg, tags: ['rg']}
    - {role: fzf, tags: ['fzf']}
    - {role: curl, tags: ['curl']}
    - {role: bash, tags: ['bash', 'bootstrap']}
    - {role: tmux, tags: ['tmux', 'bootstrap']}
    - {role: fonts, tags: ['fonts']}
    - {role: nodejs, tags: ['nodejs']}

    #- {role: package_manager, tags: ['package_manager', 'bootstrap']}
    #- {role: python, tags: ['python']}
    #- {role: node, tags: ['node']}
    #- {role: kubernetes, tags: ['kubernetes']}

