---
- name: Set up local sysadmin tooling.
  hosts: local
  roles:
    - {role: git, tags: ['git', 'base']}
    - {role: vim, tags: ['vim', 'base']}
    - {role: rg, tags: ['rg', 'base']}
    - {role: fzf, tags: ['fzf', 'base']}
    - {role: curl, tags: ['curl', 'base']}
    - {role: bash, tags: ['bash', 'base']}
    - {role: tmux, tags: ['tmux', 'base']}
    - {role: nodejs, tags: ['nodejs']}
    - {role: neovim-symlink, tags: ['neovim-symlink']}
    - {role: timer, tags: ['timer']}
    - {role: fish, tags: ['fish']}
    - {role: zsh, tags: ['zsh']}



