#!/usr/bin/env bash

# Recolor remaps
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias tmux='tmux -u'

# Listing. eza when present, ls otherwise, same letters either way. Kept in step
# with ~/.config/fish/conf.d/10-aliases.fish.
if command -v eza >/dev/null 2>&1; then
    alias ls='eza -a --color=always --group-directories-first --icons=always'
    alias ll='eza -l --color=always --group-directories-first --icons=always'
    alias la='eza -al --color=always --group-directories-first --icons=always'
    alias lt='eza -aT --color=always --group-directories-first --icons=always'
    alias l.="eza -a | grep -e '^\.'"
else
    alias ls='ls --color=auto'
    alias ll='ls -ahlF --group-directories-first'
    alias la='ls -A'
    alias lt='ls --human-readable --size -1 -S --classify'
fi

# One letter aliases
alias f='find'
alias g='git'
alias t='tmux new -AsBOFH'
alias k='kubectl'
alias l='ls'
alias m='mutt'
alias v='vim'
alias u='upg'

# Two letter aliases
alias ff='find . -type f -name'
alias gh='history|grep'
alias sv='sudo vim'

# Three letter aliases
alias ffs='sudo !!'

# systemd shenanigans
alias s='systemctl'
alias scat='systemctl cat'
alias sstat='systemctl status'
alias srl='systemctl reload'
alias sstop='systemctl stop'
alias sstart='systemctl start'
alias stimers='systemctl list-timers --all'
alias aan='sstart'
alias uit='sstop'
alias log='journalctl -eu'
alias logf='journalctl -efu'

# certificate shenanigancs
alias crt_expiration='openssl x509 -enddate -noout -in'
alias crt_info='openssl x509 -noout -text -in'
alias crt_modulus='openssl x50 -noout -modulus -in'
alias key_modulus='openssl rsa -noout -modulus -in'
alias csr_modulus='openssl csr -noout -modulus -in'
