---
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"


