---
- name: Symlink gitconfig
  file:
    src: "{{ repo_home }}/roles/git/files/gitconfig"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    state: link

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
