---
- name: Check if our user's script dir exists.
  file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/bin"
    state: directory

- name: Link our shellscripts.
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/bin/{{ item }}"
    state: link
  loop:
    - "polybar.sh"

- name: Check if our ~/.config dir exists.
  file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/polybar"
    state: directory

- name: Link our polybar config.
  file:
    src: "{{ role_path }}/files/config.ini"
    dest: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME') or default_config_dir }}/polybar/config.ini"
    state: link
    
