---
- name: Ensure nvim config directories exist
  file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') or default_config_dir }}/nvim"
    state: directory

- name: Link our migratory nvim config
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') or default_config_dir }}/nvim/init.vim"
    state: link
      
- name: Install plugins
  command: "vim +PluginInstall +qall"
