#!/usr/bin/env bash

#trap '
   #_LASTCOM="$(history 1 | sed "s/^[ ]*[0-9]*[ ]*//g")"
   #printf "\e]0;%s\a" "$_LASTCOM"
   #' DEBUG
#PS1='\[\e]0;*$_LASTCOM\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null)'; PS1='\[\e[90m\]\A\[\e[0m\] \[\e[38;5;154m\]\u\[\e[0;1m\]@\[\e[0;38;5;154m\]\H\[\e[0m\] [\[\e[38;5;122m\]\w\[\e[0m\]] : \[\e[38;5;227m\]${PS1_CMD1}\[\e[0m\] \n[\[\e[90m\]$?\[\e[0m\]] \$ '
