#!/usr/bin/env bash

# Recolor remaps
alias ls='ls --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias tmux='tmux -u'

# some more ls aliases
alias ll='ls -ahlF --group-directories-first'
alias la='ls -A'
alias l='ls -CF'

# One letter aliases
alias f='find'
alias g='git'
alias t='tmux new -AsBOFH'
alias k='kubectl'
alias l='ls'
alias m='mutt'
alias v='vim'
alias u='upg'

# Two letter aliases
alias ff='find . -type f -name'
alias gh='history|grep'
alias ll='ls -laH'
alias lt='ls --human-readable --size -1 -S --classify'
alias sv='sudo vim'

# Three letter aliases
alias ffs='sudo !!'

# systemd shenanigans
alias s='systemctl'
alias stimers='systemctl list-timers --all'
alias srl='systemctl reload'
alias sstop='systemctl stop'
alias sstart='systemctl start'
alias aan='sstart'
alias uit='sstop'
alias log='journalctl -eu'
alias logf='journalctl -efu'

# certificate shenanigancs
alias crt_expiration='openssl x509 -enddate -noout -in'
alias crt_info='openssl x509 -noout -text -in'
alias crt_modulus='openssl x50 -noout -modulus -in'
alias key_modulus='openssl rsa -noout -modulus -in'
alias csr_modulus='openssl csr -noout -modulus -in'
