---
- name: Get HOME dir
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    
- name: Install tmux
  homebrew: name=tmux state=present

- name: Copy the tmux config
  copy:
    src: tmux.conf
    dest: "{{home}}/.config/tmux.conf"

- name: Copy the tmux config addon for mac
  copy:
    src: tmux.osx.conf
    dest: "{{home}}/.config/tmux.osx.conf"

- name: Symlink to the file
  file:
    src: "{{home}}/.config/tmux.conf"
    dest: "{{home}}/.tmux.conf"
    state: link
