---   
- name: Install tmux
  homebrew: name=tmux state=present

- name: Symlink osx specific tmux conf hack
  file:
    src: "{{ repo_home }}/roles/tmux/files/tmux.osx.conf"
    dest: "{{ dotfiles_user_home }}/.tmux.osx.conf"
    state: link

