---
- name: Symlink tmux conf
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ dotfiles_user_home }}/.tmux.conf"
    state: link

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
    
- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"


