---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "Redhat"

- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"
