---
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ repo_home }}/roles/vim/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link
    force: true

- name: Clone Vundle into place...
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: "{{dotfiles_user_home}}/.vim/bundle/Vundle.vim"

- name: Install plugins
  command: "vim +PluginInstall +qall"
  #when: vim_install_plugins|bool
